language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
env:
    - TORNADO_VERSION=5.0 PYTEST_VERSION=3.6.4
    - TORNADO_VERSION=5.0 PYTEST_VERSION=4.0.0
install:
    - pip install -q tornado==$TORNADO_VERSION pytest==$PYTEST_VERSION
    - python setup.py install
script:
    - py.test --strict
